[package]
name = "puccinia_s_checkmate"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
rand = "0.8.5"

[dev-dependencies]

[profile.release]
#debug = true
lto = true
